### ISSUE TITLE
Is there a python or c++ viewer like SIBR?

### ISSUE THREAD

**Issue by oUp2Uo** [KeKsBoTer/c3dgs#10]
Hi, thanks for the great work.
It usually can compress ~100MB 3DGS ply to xMB npz.
But the viewer(https://github.com/KeKsBoTer/web-splat) is not easy to use, and it is not fast.
Is there a python or c++ viewer like SIBR using CUDA?
Thank you.

**Comment by KeKsBoTer** [comment]
Hello, 

The viewer is usually 2x faster than the SIBR viewer because it uses Hardware, not Software Rasterization (see the paper for details).  
If you experience bad performance, please let me know what graphics card you are using. It did run very well on all NVIDIA cards I tested. 

There is no C++ or CUDA viewer that can load the npz files.
You can convert the npz files back to ply with [this tool](https://github.com/KeKsBoTer/c3dgs/blob/master/npz2ply.py) and open it in the SIBR viewer.


Best
Simon

**Comment by oUp2Uo** [comment]
Thanks for the reply.

I was trying on a old PC yesterday(GTX 1050 laptop), I will try on a new PC today.
